library(traceR)
library(plyr)
traceRedit(ns = "plyr")
detach(package:plyr)

library(plyr)
n <- 17; fac <- factor(rep(1:3, length = n), levels = 1:5)
table(fac)
traceR.on()
vaggregate(1:n, fac, sum)
traceR.report()
traceR.report("rep.html", staticTree = TRUE)
traceR.off()
Remove(list = Objects())

unloadNamespace("plyr")
detach(package:traceR)
detach(package:SOAR)
sessionInfo()
